components:
- revisionName: INTERNAL_ADDON|productopsv2|_
  traits:
  - name: gateway.trait.abm.io
    runtime: post
    spec:
      path: /v2/foundation/kg/**
      servicePort: 80
      serviceName: 'prod-search-tkgone'
      routeId: "dev-search-tkgone-master-${NAMESPACE_ID}-dev"
 
