version: 1.0
name: paas-frontend
variables:
  DOCKERFILE_PATH: "/"
  IMAGE_PREFIX: ""
  IMAGE_NAME: "paas-frontend"
  cpuArch: "x86_64"
machine:
  standard:
    abm_machines:
      - default
scripts:
  - ./fw_build.sh "{{IMAGE_NAME}}" "{{FW_BRANCH_NAME}}" "{{cpuArch}}"
artifacts:
  images:
    - "{{IMAGE_PREFIX}}:{{FW_BRANCH_NAME}}_{{cpuArch}}"
notifications:
  email: