FROM node:14.18.3-alpine3.15
COPY . /app
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk add --update --no-cache python2 make gcc g++ zip
RUN export NPM_REGISTRY_URL="https://registry.npmmirror.com" && /bin/sh /app/sbin/build-standalone.sh