oap:
  image:
    tag: 8.5.0-es7
  storageType: elasticsearch7

elasticsearch:
  enabled: false
  config:
    host: elasticsearch-proxy
    port:
      http: 9200

elasticsearchEndpint: http://test.com/gateway/elasticsearch/
