#!/bin/sh
#chkconfig: 2345 80 05
#description: elasticsearch
#author: xueyong.zxy


case "$1" in
start)
    su elastic<<!
    cd /opt/elasticsearch-6.4.0
    ./bin/elasticsearch -d
!
    echo "elasticsearch startup"
    ;;  
stop)
    es_pid=`ps aux|grep elasticsearch-6.4.0 | grep -v 'grep elasticsearch-6.4.0' | awk '{print $2}'`
    kill -9 $es_pid
    echo "elasticsearch stopped"
    ;;  
restart)
    es_pid=`ps aux|grep elasticsearch-6.4.0 | grep -v 'grep elasticsearch-6.4.0' | awk '{print $2}'`
    kill -9 $es_pid
    echo "elasticsearch stopped"
    su elastic<<!
    cd /opt/elasticsearch-6.4.0
    ./bin/elasticsearch -d
!
    echo "elasticsearch startup"
    ;;  
*)
    echo "start|stop|restart"
    ;;  
esac

exit $?

# sudo chmod +x /etc/init.d/elasticsearch
# sudo chkconfig --add /etc/init.d/elasticsearch
# ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.4.0/elasticsearch-analysis-ik-6.4.0.zip
