### server config
server:
  port: ${SERVER_PORT:7001}

### management config
management:
  server:
    port: ${MANAGER_SERVER_PORT:-1}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,gateway,admin,view


ribbon:
  ConnectTimeout: 12000
  ReadTimeout: 300000
  ServerListRefreshInterval: 30000



### spring application config
spring:
  application:
    name: tesla-gateway
  cloud:
    ### 网关配置
    gateway:
      httpclient:
        response-timeout: 300s
        connect-timeout: 12000 # 连接超时时间6s
        pool:
          type: disabled
          name: gateway-connection-pool

      routes:
        - id: v2-tesla-gateway
          uri: http://127.0.0.1:7002
          predicates:
            - Path=/v2/common/gateway/**
          filters:
            - StripPrefix=3
            - PrefixPath=/actuator/admin
          order: 500

      discovery:
        locator:
          enabled: false # 如果开启，将自动将服务注册上的所有服务都可以通过网关访问

    nacos: # nacos 配置
      discovery:
        namespace: ${NACOS_NAMESPACE}
        server-addr: ${NACOS_ENDPOINT}
        watch-delay: 30000 #30s
        enabled: ${REGISTER_NACOS_ENABLED:false}
      config:
        server-addr: ${NACOS_ENDPOINT}
        namespace: ${NACOS_NAMESPACE}

  redis:
    database: ${REDIS_DB}
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
    timeout: 15000
  resources:
    add-mappings: false



  eagleeye:
    enabled: false

### tesla config
tesla:
  env: prod
  region: ${GATEWAY_REGION:"private"}
  auto-online: true #手动去触发上线，避免刚开始启动时，路由未完全初始化，出现No handler
  config:
    gateway:
      admin-token: ${AUTH_ADMIN_TOKEN:""}
      auth-address: ${ENDPOINT_PAAS_AUTHPROXY:""}
      authCookieKey: ${AUTH_COOKIE_KEY:""}
      authCookieName: ${AUTH_COOKIE_NAME:""}
      jwt-secret: ${AUTH_JWT_SECRET:""}
      tesla-auth-app: ${TESLA_AUTH_APP:""}
      tesla-auth-key: ${TESLA_AUTH_KEY:""}
      store-nacos-data-id: ${STORE_NACOS_DATA_ID:""}
      store-nacos-group: ${STORE_NACOS_GROUP:""}
      store-nacos-namespace: ${NACOS_NAMESPACE}
      store-nacos-addr: ${NACOS_ENDPOINT}
      enabled-cros: true
      default-route-data-id: abm-paas-gateway.default-route.${REGION:"default"}_${IDC_ROOM:"default"}
      enable-doc: ${GATEWAY_ENABLE_DOC:false}
      reload-config: ${GATEWAY_RELOAD_CONFIG:false}
      enable-auth: ${GATEWAY_ENABLE_AUTH:true}
      enable-switch-view: ${ENABLE_SWITCH_VIEW:false}
      aliyun-access-key: ${ALIYUN_ACCESS_KEY:""}
      aliyun-access-secret: ${ALIYUN_ACCESS_SECRET:""}
      enabled-aliyun-user-login: ${ENABLE_ALIYUN_USER_LOGIN:false}


