apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-proxy-config
data:
  elasticsearch.conf: |+
    server {
        listen       9200;
        listen  [::]:9200;
        server_name  localhost;

        # {{ .Values.elasticsearchEndpint }}
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;

            proxy_pass {{ .Values.elasticsearchEndpint }};
        }
    }
